/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/73etFZW0zcT
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Loginscreen() {
  return (
    <Card key="1" className="mx-auto max-w-sm">
      <CardHeader className="space-y-1">
        <CardTitle className="text-2xl font-bold">Entrar</CardTitle>
        <CardDescription>Insira seu e-mail abaixo para fazer login na sua conta</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="email">E-mail</Label>
            <Input id="email" placeholder="m@example.com" required type="email" />
          </div>
          <div className="space-y-2">
            <div className="flex items-center">
              <Label htmlFor="password">Senha</Label>
              <Link className="ml-auto inline-block text-sm underline" href="#">
                Esqueceu sua senha?
              </Link>
            </div>
            <Input id="password" required type="password" />
          </div>
          <Button className="w-full" type="submit">
            Entrar
          </Button>
          <Button className="w-full" variant="outline">
            Entrar com Google
          </Button>
        </div>
        <div className="mt-4 text-center text-sm">
          Não tem uma conta?
          <Link className="underline" href="#">
            Cadastre-se
          </Link>
        </div>
      </CardContent>
    </Card>
  )
}
